In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [35]:
scenario_name = 'test_manhattan_scenario_1'
base_dir = f'../data/processed/{scenario_name}'

In [36]:
dfs = {}
for f in os.listdir(base_dir):
    if f.endswith('.parquet'):
        file_path = os.path.join(base_dir, f)
        dfs[os.path.splitext(f)[0]] = pd.read_parquet(file_path)
        print(f"Loaded {f} into dfs['{os.path.splitext(f)[0]}']")

Loaded request_features.parquet into dfs['request_features']
Loaded vehicle_features.parquet into dfs['vehicle_features']
Loaded request_request_graph.parquet into dfs['request_request_graph']
Loaded vehicle_request_graph.parquet into dfs['vehicle_request_graph']

In [37]:
# read pickle file
with open('/Users/hoda_hamdy/Documents/Projects/fleetpy/FleetPy/studies/manhattan_case_study/results/test_manhattan_scenario_1/train/0/vehicle_request_graph.pkl', 'rb') as f:
    vehicle_request_graph = pd.read_pickle(f)
vehicle_request_graph

{2: {3179577: {'travel_cost': 177.29676912058875,
   'travel_time': 177.29676912058875,
   'travel_dist': 876.895}},
 3: {3179577: {'travel_cost': 91.18119554773135,
   'travel_time': 91.18119554773135,
   'travel_dist': 402.68000000000006}},
 6: {3179577: {'travel_cost': 177.29676912058875,
   'travel_time': 177.29676912058875,
   'travel_dist': 927.8510000000001}},
 10: {3179577: {'travel_cost': 167.16552517084082,
   'travel_time': 167.16552517084082,
   'travel_dist': 872.512}},
 11: {3179577: {'travel_cost': 43.05778678642869,
   'travel_time': 43.05778678642869,
   'travel_dist': 223.865}},
 16: {3179577: {'travel_cost': 324.1998063919337,
   'travel_time': 324.1998063919337,
   'travel_dist': 1655.855}},
 19: {3179577: {'travel_cost': 227.95298886932838,
   'travel_time': 227.95298886932838,
   'travel_dist': 1207.138}},
 22: {3179577: {'travel_cost': 75.98432962310946,
   'travel_time': 75.98432962310946,
   'travel_dist': 322.61400000000003}},
 25: {3179577: {'travel_cost': 240.6170438065133,
   'travel_time': 240.6170438065133,
   'travel_dist': 1201.7269999999999}},
 26: {3179577: {'travel_cost': 273.54358664319403,
   'travel_time': 273.54358664319403,
   'travel_dist': 1437.695}},
 34: {3179577: {'travel_cost': 124.10773838441212,
   'travel_time': 124.10773838441212,
   'travel_dist': 648.559}},
 35: {3179577: {'travel_cost': 455.90597773865676,
   'travel_time': 455.90597773865676,
   'travel_dist': 2350.0609999999997}},
 40: {3179577: {'travel_cost': 400.1841360150431,
   'travel_time': 400.1841360150431,
   'travel_dist': 2006.9990000000003}},
 41: {3179577: {'travel_cost': 260.8795317060091,
   'travel_time': 260.8795317060091,
   'travel_dist': 1364.9569999999999}},
 45: {3179577: {'travel_cost': 293.8060745426899,
   'travel_time': 293.8060745426899,
   'travel_dist': 1447.0100000000002}},
 50: {3179577: {'travel_cost': 195.0264460326476,
   'travel_time': 195.0264460326476,
   'travel_dist': 969.6729999999999}},
 63: {3179577: {'travel_cost': 162.09990319596685,
   'travel_time': 162.09990319596685,
   'travel_dist': 848.681}},
 66: {3179577: {'travel_cost': 250.74828775626122,
   'travel_time': 250.74828775626122,
   'travel_dist': 1249.908}},
 70: {3179577: {'travel_cost': 136.77179332159702,
   'travel_time': 136.77179332159702,
   'travel_dist': 710.7180000000001}},
 103: {3179577: {'travel_cost': 311.5357514547488,
   'travel_time': 311.5357514547488,
   'travel_dist': 1543.499}},
 105: {3179577: {'travel_cost': 225.4201778818914,
   'travel_time': 225.4201778818914,
   'travel_dist': 1122.403}},
 106: {3179577: {'travel_cost': 468.5700326758417,
   'travel_time': 468.5700326758417,
   'travel_dist': 2427.5389999999998}},
 113: {3179577: {'travel_cost': 319.1341844170597,
   'travel_time': 319.1341844170597,
   'travel_dist': 1520.111}},
 117: {3179577: {'travel_cost': 283.674830592942,
   'travel_time': 283.674830592942,
   'travel_dist': 1444.879}},
 119: {3179577: {'travel_cost': 407.7825689773541,
   'travel_time': 407.7825689773541,
   'travel_dist': 2047.651}}}

In [38]:
timestep = 120

In [39]:
# read pickle file
with open(f'/Users/hoda_hamdy/Documents/Projects/fleetpy/FleetPy/studies/manhattan_case_study/results/test_manhattan_scenario_1/train/{timestep}/init_assignments.pkl', 'rb') as f:
    init_assignments = pd.read_pickle(f)
init_assignments

{11: (11, 3179577), 112: (112, 3181469), 119: (119, 3180767)}

In [40]:
# read pickle file
with open(f'/Users/hoda_hamdy/Documents/Projects/fleetpy/FleetPy/studies/manhattan_case_study/results/test_manhattan_scenario_1/train/{timestep}/assignments.pkl', 'rb') as f:
    assignments = pd.read_pickle(f)
assignments

{11: (11, 3179577),
 76: (76, 3179802),
 112: (112, 3181469),
 119: (119, 3180767)}

In [41]:
dfs['request_features'].query(f'timestep == {timestep}')

,clustering_coeff,d_lat,d_lon,demand_supply_ratio,direct_td,direct_tt,id,in_degree_from_requests,in_degree_from_vehicles,in_degree_total,...,route_directness,rq_time,status,time_until_earliest,time_until_latest,time_window_urgency,time_window_width,timestep,tw_pe,tw_pl
8,0.000000,-73.983814,40.740787,0.0000,2399.648,501.496576,3179577,0,1,1,...,81585.992350,0,5,0,360,0.002778,480,120,0,480
9,0.194444,-73.988869,40.744533,0.0625,531.061,124.107738,3180767,1,8,9,...,73795.369907,30,3,0,390,0.002564,480,120,30,510
10,0.000000,-73.992716,40.724097,0.0000,1832.137,478.701277,3181469,0,10,10,...,86295.776439,90,3,0,450,0.002222,480,120,90,570
11,0.040936,-73.986413,40.740211,0.0400,236.123,55.721842,3179802,0,18,18,...,97338.197709,120,1,0,480,0.002083,480,120,120,600

In [42]:
dfs['request_features'].columns

Index(['clustering_coeff', 'd_lat', 'd_lon', 'demand_supply_ratio',
       'direct_td', 'direct_tt', 'id', 'in_degree_from_requests',
       'in_degree_from_vehicles', 'in_degree_total', 'locked',
       'manhattan_distance', 'max_trip_time', 'nearby_requests',
       'nearby_vehicles', 'nx_combined_betweenness_centrality',
       'nx_combined_closeness_centrality', 'nx_combined_degree_centrality',
       'nx_combined_pagerank', 'nx_rr_betweenness_centrality',
       'nx_rr_closeness_centrality', 'nx_rr_degree_centrality',
       'nx_rr_pagerank', 'o_lat', 'o_lon', 'origin_dest_bearing',
       'out_degree_to_requests', 'out_degree_to_vehicles', 'out_degree_total',
       'request_age', 'request_vehicle_in_ratio', 'request_vehicle_out_ratio',
       'route_directness', 'rq_time', 'status', 'time_until_earliest',
       'time_until_latest', 'time_window_urgency', 'time_window_width',
       'timestep', 'tw_pe', 'tw_pl'],
      dtype='object')

In [46]:
dfs['request_request_graph'].query(f'timestep == {timestep}')[['source', 'target', 'init_assign', 'optimal_assign']]

   source  target  init_assign  optimal_assign
0       1       2            0               0

In [47]:
dfs['vehicle_request_graph'].query(f'timestep == {timestep}')[['source', 'target', 'init_assign', 'optimal_assign']]

    source  target  init_assign  optimal_assign
0        4       1            0               0
1        4       3            0               0
2        4       2            0               0
3       11       0            1               1
4       15       3            0               0
5       16       1            0               0
6       17       1            0               0
7       28       1            0               0
8       28       3            0               0
9       29       1            0               0
10      29       3            0               0
11      32       1            0               0
12      33       2            0               0
13      40       1            0               0
14      40       2            0               0
15      45       1            0               0
16      45       2            0               0
17      46       3            0               0
18      47       1            0               0
19      49       1            0               0
20      71       3            0               0
21      76       1            0               1
22      86       1            0               0
23      86       3            0               0
24      97       1            0               0
25      97       3            0               0
26      97       2            0               0
27     103       1            0               0
28     103       2            0               0
29     110       1            0               0
30     111       3            0               0
31     112       1            0               0
32     112       3            1               1
33     113       1            0               0
34     113       2            0               0
35     119       1            0               0
36     119       2            1               1