In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
scenario_name = 'test_manhattan_scenario_1'
base_dir = f'data/{scenario_name}/processed'

In [3]:
dfs = {}
for f in os.listdir(base_dir):
    if f.endswith('.parquet'):
        file_path = os.path.join(base_dir, f)
        dfs[os.path.splitext(f)[0]] = pd.read_parquet(file_path)
        print(f"Loaded {f} into dfs['{os.path.splitext(f)[0]}']")

Loaded request_features.parquet into dfs['request_features']
Loaded vehicle_features.parquet into dfs['vehicle_features']
Loaded request_request_graph.parquet into dfs['request_request_graph']
Loaded vehicle_request_graph.parquet into dfs['vehicle_request_graph']

In [9]:
# read pickle file
with open('/Users/hoda_hamdy/Documents/Projects/fleetpy/FleetPy/studies/manhattan_case_study/results/test_manhattan_scenario_1/train/600/vehicle_request_graph.pkl', 'rb') as f:
    vehicle_request_graph = pd.read_pickle(f)
vehicle_request_graph

{11: {3179577: {'travel_cost': 529.3574963743292,
   'travel_time': 529.3574963743292,
   'travel_dist': 2470.817}},
 15: {3181771: {'travel_cost': 316.60137342962275,
   'travel_time': 316.60137342962275,
   'travel_dist': 1313.7820000000002}},
 26: {3178852: {'travel_cost': 445.7747337889088,
   'travel_time': 445.7747337889088,
   'travel_dist': 2217.941}},
 27: {3181771: {'travel_cost': 288.74045256781596,
   'travel_time': 288.74045256781596,
   'travel_dist': 1212.4759999999999}},
 28: {3181771: {'travel_cost': 293.8060745426899,
   'travel_time': 293.8060745426899,
   'travel_dist': 1300.9160000000002}},
 29: {3181771: {'travel_cost': 311.5357514547488,
   'travel_time': 311.5357514547488,
   'travel_dist': 1366.5700000000002}},
 31: {3181771: {'travel_cost': 233.01861084420233,
   'travel_time': 233.01861084420233,
   'travel_dist': 970.0319999999999}},
 32: {3178801: {'travel_cost': np.float64(305.1185624421857),
   'travel_time': np.float64(305.1185624421857),
   'travel_dist': np.float64(1342.1083959626003)}},
 33: {3178852: {'travel_cost': 174.76395813315176,
   'travel_time': 174.76395813315176,
   'travel_dist': 650.4449999999999},
  3180283: {'travel_cost': 0.0, 'travel_time': 0.0, 'travel_dist': 0.0},
  3181780: {'travel_cost': 258.34672071857216,
   'travel_time': 258.34672071857216,
   'travel_dist': 1145.693},
  3179479: {'travel_cost': 159.56709220852986,
   'travel_time': 159.56709220852986,
   'travel_dist': 696.7049999999999}},
 35: {3178852: {'travel_cost': 395.1185140401692,
   'travel_time': 395.1185140401692,
   'travel_dist': 2008.0029999999997}},
 36: {3179211: {'travel_cost': 233.01861084420233,
   'travel_time': 233.01861084420233,
   'travel_dist': 1172.953}},
 40: {3178852: {'travel_cost': np.float64(256.20796466832013),
   'travel_time': np.float64(256.20796466832013),
   'travel_dist': np.float64(1264.947617242809)}},
 44: {3179211: {'travel_cost': 309.0029404673118,
   'travel_time': 309.0029404673118,
   'travel_dist': 1511.071}},
 45: {3178852: {'travel_cost': 367.2575931783624,
   'travel_time': 367.2575931783624,
   'travel_dist': 1811.3329999999999}},
 46: {3181771: {'travel_cost': np.float64(127.03428122109287),
   'travel_time': np.float64(127.03428122109287),
   'travel_dist': np.float64(557.4924373260665)}},
 47: {3179521: {'travel_cost': np.float64(252.53358664319407),
   'travel_time': np.float64(252.53358664319407),
   'travel_dist': np.float64(1120.195080321544)},
  3181771: {'travel_cost': np.float64(401.969434901976),
   'travel_time': np.float64(401.969434901976),
   'travel_dist': np.float64(1761.439080321544)}},
 53: {3181897: {'travel_cost': np.float64(173.66520208289967),
   'travel_time': np.float64(173.66520208289967),
   'travel_dist': np.float64(914.6793799775717)}},
 55: {3181771: {'travel_cost': 410.3153799647911,
   'travel_time': 410.3153799647911,
   'travel_dist': 1658.6399999999999}},
 56: {3179211: {'travel_cost': np.float64(6.634054937184937),
   'travel_time': np.float64(6.634054937184937),
   'travel_dist': np.float64(31.36599417715282)}},
 69: {3178491: {'travel_cost': np.float64(172.43958010802572),
   'travel_time': np.float64(172.43958010802572),
   'travel_dist': np.float64(777.1706653351996)}},
 71: {3181771: {'travel_cost': 172.23114714571477,
   'travel_time': 172.23114714571477,
   'travel_dist': 696.514}},
 74: {3179211: {'travel_cost': 281.14201960550497,
   'travel_time': 281.14201960550497,
   'travel_dist': 1377.7640000000001}},
 76: {3179816: {'travel_cost': np.float64(80.47681752260533),
   'travel_time': np.float64(80.47681752260533),
   'travel_dist': np.float64(265.1620610444711)}},
 77: {3179211: {'travel_cost': 250.74828775626122,
   'travel_time': 250.74828775626122,
   'travel_dist': 1208.306}},
 78: {3181771: {'travel_cost': 288.74045256781596,
   'travel_time': 288.74045256781596,
   'travel_dist': 1230.0130000000001}},
 86: {3181771: {'travel_cost': 359.6591602160514,
   'travel_time': 359.6591602160514,
   'travel_dist': 1483.5300000000002}},
 87: {3179211: {'travel_cost': 217.82174491958045,
   'travel_time': 217.82174491958045,
   'travel_dist': 1080.276}},
 88: {3181771: {'travel_cost': 283.674830592942,
   'travel_time': 283.674830592942,
   'travel_dist': 1143.3020000000001}},
 94: {3179211: {'travel_cost': 195.0264460326476,
   'travel_time': 195.0264460326476,
   'travel_dist': 943.338}},
 96: {3181771: {'travel_cost': 316.60137342962275,
   'travel_time': 316.60137342962275,
   'travel_dist': 1344.2710000000002}},
 97: {3180201: {'travel_cost': np.float64(243.20109874369817),
   'travel_time': np.float64(243.20109874369817),
   'travel_dist': np.float64(1048.8855294175532)},
  3181771: {'travel_cost': np.float64(334.3822942914295),
   'travel_time': np.float64(334.3822942914295),
   'travel_dist': np.float64(1367.8185294175532)}},
 103: {3178852: {'travel_cost': 372.32321515323633,
   'travel_time': 372.32321515323633,
   'travel_dist': 1875.187}},
 104: {3179211: {'travel_cost': 154.5014702336559,
   'travel_time': 154.5014702336559,
   'travel_dist': 724.262}},
 105: {3178852: {'travel_cost': 448.3075447763458,
   'travel_time': 448.3075447763458,
   'travel_dist': 2254.622}},
 107: {3181771: {'travel_cost': 357.12634922861446,
   'travel_time': 357.12634922861446,
   'travel_dist': 1464.373}},
 109: {3179211: {'travel_cost': 336.8638613291186,
   'travel_time': 336.8638613291186,
   'travel_dist': 1697.657}},
 111: {3182147: {'travel_cost': np.float64(425.56067885172394),
   'travel_time': np.float64(425.56067885172394),
   'travel_dist': np.float64(1749.182941769246)}},
 112: {3181771: {'travel_cost': np.float64(178.5180130703367),
   'travel_time': np.float64(178.5180130703367),
   'travel_dist': np.float64(759.5758655323461)},
  3181469: {'travel_cost': np.float64(457.1272216884047),
   'travel_time': np.float64(457.1272216884047),
   'travel_dist': np.float64(1879.8628655323462)}},
 113: {3178852: {'travel_cost': 367.2575931783624,
   'travel_time': 367.2575931783624,
   'travel_dist': 1803.48}},
 114: {3181771: {'travel_cost': 352.0607272537405,
   'travel_time': 352.0607272537405,
   'travel_dist': 1419.5500000000002}},
 117: {3178682: {'travel_cost': np.float64(146.3586592462189),
   'travel_time': np.float64(146.3586592462189),
   'travel_dist': np.float64(764.1283037332047)},
  3178852: {'travel_cost': np.float64(435.09911181403487),
   'travel_time': np.float64(435.09911181403487),
   'travel_dist': np.float64(2158.1803037332047)}},
 119: {3178852: {'travel_cost': np.float64(295.42667231655554),
   'travel_time': np.float64(295.42667231655554),
   'travel_dist': np.float64(1349.5631751786425)},
  3181780: {'travel_cost': np.float64(303.0251052788665),
   'travel_time': np.float64(303.0251052788665),
   'travel_dist': np.float64(1337.6741751786424)},
  3179479: {'travel_cost': np.float64(37.0799515979834),
   'travel_time': np.float64(37.0799515979834),
   'travel_dist': np.float64(160.52717517864255)}}}

In [15]:
# read pickle file
with open('/Users/hoda_hamdy/Documents/Projects/fleetpy/FleetPy/studies/manhattan_case_study/results/test_manhattan_scenario_1/train/450/init_assignments.pkl', 'rb') as f:
    init_assignments = pd.read_pickle(f)
init_assignments

{11: (11, 3179577),
 33: (33, 3180283),
 47: (47, 3179521),
 53: (53, 3181897),
 69: (69, 3178491),
 76: (76, 3179816),
 97: (97, 3180201),
 111: (111, 3182147),
 112: (112, 3181469),
 117: (117, 3178682),
 119: (119, 3179479)}

In [14]:
dfs['request_features'].query('timestep == 15')

,id,o_lat,o_lon,d_lat,d_lon,rq_time,tw_pe,tw_pl,direct_tt,direct_td,...,clustering_coeff,nx_combined_degree_centrality,nx_combined_betweenness_centrality,nx_combined_closeness_centrality,nx_combined_pagerank,timestep,nx_rr_degree_centrality,nx_rr_betweenness_centrality,nx_rr_closeness_centrality,nx_rr_pagerank
95,3179577,-73.972719,40.759104,-73.983814,40.740787,0,0,480,501.496576,2399.648,...,0.666667,0.076923,0.000000,0.274887,0.051338,15,0.375,0.000000,0.250000,0.079191
96,3181469,-74.003153,40.734891,-73.992716,40.724097,90,90,570,478.701277,1832.137,...,0.000000,0.076923,0.000943,0.243590,0.051736,15,0.375,0.026786,0.375000,0.125712
97,3180201,-73.999425,40.744010,-74.003417,40.714119,180,180,660,957.402553,4031.623,...,0.400000,0.096154,0.023944,0.315482,0.082875,15,0.500,0.142857,0.390625,0.129320
98,3182147,-74.005145,40.729471,-73.941667,40.830160,180,180,660,2626.524994,13062.370,...,0.166667,0.076923,0.000000,0.357782,0.130661,15,0.375,0.000000,0.556818,0.236175
99,3179521,-73.983064,40.730653,-73.990945,40.733978,240,240,720,172.231147,759.989,...,0.333333,0.057692,0.000377,0.019231,0.009583,15,0.250,0.000000,0.000000,0.049649
100,3181897,-73.955406,40.776870,-73.990203,40.731964,270,270,750,1284.135171,6245.765,...,0.000000,0.019231,0.000000,0.019231,0.012441,15,0.000,0.000000,0.000000,0.000000
101,3180283,-74.000683,40.751951,-74.003806,40.753273,270,270,750,233.018611,910.128,...,0.666667,0.057692,0.000000,0.241531,0.047263,15,0.250,0.000000,0.346154,0.113051
102,3178491,-74.014220,40.704633,-73.949815,40.807073,360,360,840,2697.443702,14556.779,...,0.000000,0.153846,0.000000,0.153846,0.052453,15,0.000,0.000000,0.000000,0.000000
103,3179479,-73.996204,40.748428,-73.987355,40.738918,360,360,840,372.323215,1622.834,...,0.218182,0.211538,0.006599,0.115385,0.020062,15,0.625,0.000000,0.000000,0.049649
104,3179816,-73.984579,40.742728,-74.005106,40.731836,420,420,900,620.538692,2613.221,...,0.068376,0.519231,0.044306,0.523504,0.166686,15,0.750,0.187500,0.500000,0.167604
105,3178682,-73.974408,40.750764,-73.984773,40.734012,420,420,900,562.284039,2502.752,...,0.051383,0.442308,0.026018,0.403846,0.092466,15,0.250,0.000000,0.000000,0.049649

In [13]:
dfs['request_request_graph'].query('timestep == 15')

,source,target,tt_origin1_dest1,tt_between_pickups,tt_pickup1_dropoff2,tt_dropoff1_pickup2,tt_origin2_dest2,tt_between_dropoffs,common_request_neighbors,common_vehicle_neighbors,...,destination_proximity,pooling_detour_ratio,spatial_compatibility,extra_waiting_time,extra_time_ratio,ride_sharing_efficiency,overall_pooling_score,timestep,opt_assign,init_assign
0,8,0,372.323215,650.932424,359.659160,618.005881,501.496576,195.026446,1,0,...,2.513240,0.002702,0.248156,0.0,0.542029,0.648496,0.0,15,0.0,0.0
1,8,2,372.323215,255.813910,1051.116560,265.945154,957.402553,747.179241,1,0,...,0.515175,0.002059,0.300841,0.0,0.200000,0.833333,0.0,15,0.0,0.0
2,8,3,372.323215,597.743393,2074.372199,549.619984,2626.524994,2370.711084,0,0,...,0.172352,0.009033,0.125730,0.0,0.183277,0.845111,0.0,15,0.0,0.0
3,8,6,372.323215,172.231147,329.265428,567.349661,233.018611,683.858967,0,0,...,0.531514,0.003011,0.294891,0.0,0.799163,0.555814,0.0,15,0.0,0.0
4,8,9,372.323215,286.207642,557.218417,172.231147,620.538692,509.095008,2,0,...,0.503592,0.003449,0.233092,0.0,0.173469,0.852174,0.0,15,0.0,0.0
5,0,9,501.496576,455.905978,1066.313426,83.582763,620.538692,630.669936,0,0,...,0.419564,0.002543,0.208565,0.0,0.074492,0.930672,0.0,15,0.0,0.0
6,10,0,562.284039,238.084233,329.265428,726.916753,501.496576,303.937318,1,0,...,4.281213,0.000795,0.644723,0.0,0.000000,1.000000,0.0,15,0.0,0.0
7,10,9,562.284039,334.331050,954.869742,314.068562,620.538692,529.357496,0,0,...,0.442093,0.002288,0.226269,0.0,0.254818,0.796928,0.0,15,0.0,0.0
8,2,1,957.402553,354.593538,734.515186,706.654265,478.701277,395.118514,0,0,...,0.813895,0.001602,0.366495,0.0,0.000000,1.000000,0.0,15,0.0,0.0
9,2,6,957.402553,301.404508,417.913813,1018.190017,233.018611,995.394718,0,0,...,0.832937,0.002012,0.403015,0.0,0.285106,0.778146,0.0,15,0.0,0.0
10,1,3,478.701277,202.624879,2527.745365,344.462294,2626.524994,2763.296787,0,0,...,0.152800,0.007929,0.127855,0.0,0.110930,0.900147,0.0,15,0.0,0.0
11,4,1,172.231147,481.234088,341.929483,309.002940,478.701277,314.068562,0,0,...,2.767583,0.005007,0.277869,0.0,0.474708,0.678100,0.0,15,0.0,0.0
12,4,9,172.231147,425.512246,542.021551,339.396672,620.538692,369.790404,0,0,...,0.634496,0.005645,0.335234,0.0,0.428115,0.700224,0.0,15,0.0,0.0
13,9,2,620.538692,377.388837,858.622925,412.848191,957.402553,615.473070,0,0,...,1.740736,0.001241,0.310003,0.0,0.235955,0.809091,0.0,15,0.0,0.0
14,9,3,620.538692,661.063668,2206.078370,162.099903,2626.524994,2598.664073,0,0,...,0.130330,0.006774,0.090947,0.0,0.049922,0.952452,0.0,15,0.0,0.0

In [12]:
dfs['vehicle_request_graph'].query('timestep == 20')

,source,target,travel_time,travel_dist,common_request_neighbors,common_vehicle_neighbors,total_common_neighbors,exclusive_src_requests,exclusive_tgt_requests,exclusive_src_vehicles,...,is_locked,arrival_slack,earliest_slack,time_window_compatibility,time_feasibility_score,normalized_arrival_time,distance_to_vehicle,timestep,opt_assign,init_assign
0,11,0,529.357496,2470.817000,0,0,0,1,1,0,...,1.0,0.000000,0.000000,0.000000,0.0,2.352828,1.355752,20,1.0,1.0
1,15,14,316.601373,1313.782000,0,0,0,1,1,0,...,0.0,133.398627,-346.601373,0.277914,1.0,0.722086,1.022551,20,0.0,0.0
2,26,15,445.774734,2217.941000,0,0,0,1,6,0,...,0.0,4.225266,-475.774734,0.008803,1.0,0.991197,1.625785,20,0.0,0.0
3,27,14,288.740453,1212.476000,0,0,0,1,1,0,...,0.0,161.259547,-318.740453,0.335957,1.0,0.664043,0.742631,20,0.0,0.0
4,28,14,293.806075,1300.916000,0,0,0,1,1,0,...,0.0,156.193925,-323.806075,0.325404,1.0,0.674596,0.912319,20,0.0,0.0
5,29,14,311.535751,1366.570000,0,0,0,1,1,0,...,0.0,138.464249,-341.535751,0.288467,1.0,0.711533,1.128212,20,0.0,0.0
6,31,14,233.018611,970.032000,0,0,0,1,1,0,...,0.0,216.981389,-263.018611,0.452045,1.0,0.547955,0.815047,20,0.0,0.0
7,32,11,305.118562,1342.108396,0,0,0,1,4,0,...,1.0,0.000000,0.000000,0.000000,0.0,0.885664,0.045856,20,1.0,1.0
8,33,15,174.763958,650.445000,3,0,3,1,3,0,...,0.0,275.236042,-204.763958,0.573408,1.0,0.426592,0.300261,20,0.0,0.0
9,33,6,0.000000,0.000000,1,0,1,3,0,0,...,1.0,0.000000,0.000000,0.000000,0.0,0.687500,0.000000,20,1.0,1.0
10,33,13,258.346721,1145.693000,0,0,0,4,1,0,...,0.0,161.653279,-318.346721,0.336778,1.0,0.663222,0.137648,20,1.0,1.0
11,33,8,159.567092,696.705000,1,0,1,3,4,0,...,0.0,80.432908,-399.567092,0.167569,1.0,0.832431,0.509660,20,0.0,0.0
12,35,15,395.118514,2008.003000,0,0,0,1,6,0,...,0.0,54.881486,-425.118514,0.114336,1.0,0.885664,0.576505,20,0.0,0.0
13,36,12,233.018611,1172.953000,0,0,0,1,0,0,...,0.0,126.981389,-353.018611,0.264545,1.0,0.735455,0.299269,20,0.0,0.0
14,40,15,256.207965,1264.947617,0,0,0,1,6,0,...,0.0,193.792035,-286.207965,0.403733,1.0,0.596267,1.243241,20,1.0,1.0
15,44,12,309.002940,1511.071000,0,0,0,1,0,0,...,0.0,50.997060,-429.002940,0.106244,1.0,0.893756,1.462092,20,0.0,0.0
16,45,15,367.257593,1811.333000,0,0,0,1,6,0,...,0.0,82.742407,-397.257593,0.172380,1.0,0.827620,1.621815,20,0.0,0.0
17,46,14,127.034281,557.492437,0,0,0,1,1,0,...,0.0,322.965719,-157.034281,0.672845,1.0,0.327155,0.498927,20,1.0,1.0
18,47,4,252.533587,1120.195080,1,0,1,1,2,0,...,1.0,0.000000,0.000000,0.000000,0.0,1.276112,0.623850,20,1.0,1.0
19,47,14,401.969435,1761.439080,0,0,0,2,1,0,...,0.0,48.030565,-431.969435,0.100064,1.0,0.899936,1.423006,20,0.0,0.0
20,53,5,173.665202,914.679380,0,0,0,1,0,0,...,1.0,0.000000,0.000000,0.000000,0.0,1.049303,0.654211,20,1.0,1.0
21,55,14,410.315380,1658.640000,0,0,0,1,1,0,...,0.0,39.684620,-440.315380,0.082676,1.0,0.917324,1.103974,20,0.0,0.0
22,56,12,6.634055,31.365994,0,0,0,1,0,0,...,0.0,353.365945,-126.634055,0.736179,1.0,0.263821,0.039791,20,1.0,1.0
23,69,7,172.439580,777.170665,0,0,0,1,0,0,...,1.0,0.000000,0.000000,0.000000,0.0,0.859249,0.176293,20,1.0,1.0
24,71,14,172.231147,696.514000,0,0,0,1,1,0,...,0.0,277.768853,-202.231147,0.578685,1.0,0.421315,0.466619,20,0.0,0.0
25,74,12,281.142020,1377.764000,0,0,0,1,0,0,...,0.0,78.857980,-401.142020,0.164287,1.0,0.835713,1.240834,20,0.0,0.0
26,76,9,80.476818,265.162061,0,0,0,1,2,0,...,1.0,0.000000,0.000000,0.000000,0.0,0.542660,0.155072,20,1.0,1.0
27,77,12,250.748288,1208.306000,0,0,0,1,0,0,...,0.0,109.251712,-370.748288,0.227608,1.0,0.772392,1.298839,20,0.0,0.0
28,78,14,288.740453,1230.013000,0,0,0,1,1,0,...,0.0,161.259547,-318.740453,0.335957,1.0,0.664043,0.224721,20,0.0,0.0
29,86,14,359.659160,1483.530000,0,0,0,1,1,0,...,0.0,90.340840,-389.659160,0.188210,1.0,0.811790,0.955618,20,0.0,0.0
30,87,12,217.821745,1080.276000,0,0,0,1,0,0,...,0.0,142.178255,-337.821745,0.296205,1.0,0.703795,0.903318,20,0.0,0.0
31,88,14,283.674831,1143.302000,0,0,0,1,1,0,...,0.0,166.325169,-313.674831,0.346511,1.0,0.653489,0.531343,20,0.0,0.0
32,94,12,195.026446,943.338000,0,0,0,1,0,0,...,0.0,164.973554,-315.026446,0.343695,1.0,0.656305,1.077119,20,0.0,0.0
33,96,14,316.601373,1344.271000,0,0,0,1,1,0,...,0.0,133.398627,-346.601373,0.277914,1.0,0.722086,0.310997,20,0.0,0.0
34,97,2,243.201099,1048.885529,0,0,0,2,3,0,...,1.0,0.000000,0.000000,0.000000,0.0,1.381669,0.228849,20,1.0,1.0
35,97,14,334.382294,1367.818529,0,0,0,2,1,0,...,0.0,115.617706,-364.382294,0.240870,1.0,0.759130,0.316262,20,0.0,0.0
36,103,15,372.323215,1875.187000,0,0,0,1,6,0,...,0.0,77.676785,-402.323215,0.161827,1.0,0.838173,1.811814,20,0.0,0.0
37,104,12,154.501470,724.262000,0,0,0,1,0,0,...,0.0,205.498530,-274.501470,0.428122,1.0,0.571878,0.255146,20,0.0,0.0
38,105,15,448.307545,2254.622000,0,0,0,1,6,0,...,0.0,1.692455,-478.307545,0.003526,1.0,0.996474,1.774226,20,0.0,0.0
39,107,14,357.126349,1464.373000,0,0,0,1,1,0,...,0.0,92.873651,-387.126349,0.193487,1.0,0.806513,1.056586,20,0.0,0.0
40,109,12,336.863861,1697.657000,0,0,0,1,0,0,...,0.0,23.136139,-456.863861,0.048200,1.0,0.951800,1.451058,20,0.0,0.0
41,111,3,425.560679,1749.182942,0,0,0,1,0,0,...,1.0,0.000000,0.000000,0.000000,0.0,1.761585,1.037354,20,1.0,1.0
42,112,14,178.518013,759.575866,0,0,0,2,1,0,...,0.0,271.481987,-208.518013,0.565587,1.0,0.434413,0.831368,20,0.0,0.0
43,112,1,457.127222,1879.862866,1,0,1,1,1,0,...,1.0,0.000000,0.000000,0.000000,0.0,2.014848,1.069445,20,1.0,1.0
44,113,15,367.257593,1803.480000,0,0,0,1,6,0,...,0.0,82.742407,-397.257593,0.172380,1.0,0.827620,1.956169,20,0.0,0.0
45,114,14,352.060727,1419.550000,0,0,0,1,1,0,...,0.0,97.939273,-382.060727,0.204040,1.0,0.795960,0.275496,20,0.0,0.0
46,117,10,146.358659,764.128304,0,0,0,2,2,0,...,1.0,0.000000,0.000000,0.000000,0.0,0.679914,0.410694,20,1.0,1.0
47,117,15,435.099112,2158.180304,0,0,0,2,6,0,...,0.0,14.900888,-465.099112,0.031044,1.0,0.968956,2.251664,20,0.0,0.0
48,119,15,295.426672,1349.563175,2,0,2,1,4,0,...,0.0,154.573328,-325.426672,0.322028,1.0,0.677972,0.373605,20,0.0,0.0
49,119,13,303.025105,1337.674175,0,0,0,3,1,0,...,0.0,116.974895,-363.025105,0.243698,1.0,0.756302,0.686382,20,0.0,0.0
50,119,8,37.079952,160.527175,0,0,0,3,5,0,...,0.0,202.920048,-277.079952,0.422750,1.0,0.577250,0.055829,20,1.0,1.0

In [8]:
dfs['vehicle_features'].query('timestep >=10 & timestep < 30 & id == 11')

,id,type,status,soc,lat,lon,in_degree,out_degree,in_degree_from_requests,out_degree_to_requests,...,nx_vr_degree_centrality,nx_vr_betweenness_centrality,nx_vr_closeness_centrality,nx_vr_pagerank,nx_combined_degree_centrality,nx_combined_betweenness_centrality,nx_combined_closeness_centrality,nx_combined_pagerank,earliest_arrival,timestep
1211,11,default_vehtype,10,0.644902,-73.976579,40.750714,0,1,0,1,...,0.025641,0.0,0.0,0.015072,0.025641,0.0,0.0,0.010157,604.980129,10
1331,11,default_vehtype,10,0.644887,-73.977468,40.749495,0,1,0,1,...,0.031250,0.0,0.0,0.018726,0.031250,0.0,0.0,0.012909,670.839483,11
1451,11,default_vehtype,10,0.644871,-73.978365,40.748266,0,2,0,2,...,0.040816,0.0,0.0,0.012027,0.040816,0.0,0.0,0.008796,830.412844,12
1571,11,default_vehtype,10,0.644857,-73.979181,40.747146,0,2,0,2,...,0.044444,0.0,0.0,0.013055,0.044444,0.0,0.0,0.009716,830.415978,13
1691,11,default_vehtype,10,0.644845,-73.979903,40.746155,0,3,0,3,...,0.052632,0.0,0.0,0.010298,0.052632,0.0,0.0,0.006505,653.117044,14
1811,11,default_vehtype,10,0.644832,-73.980642,40.745149,0,3,0,3,...,0.057692,0.0,0.0,0.011274,0.057692,0.0,0.0,0.006725,653.114556,15
1931,11,default_vehtype,10,0.644818,-73.981410,40.744088,0,3,0,3,...,0.053571,0.0,0.0,0.010593,0.053571,0.0,0.0,0.007091,962.118143,16
2051,11,default_vehtype,10,0.644805,-73.982173,40.743041,0,3,0,3,...,0.060000,0.0,0.0,0.012005,0.060000,0.0,0.0,0.007789,1033.037496,17
2171,11,default_vehtype,10,0.644792,-73.982935,40.741994,0,2,0,2,...,0.044444,0.0,0.0,0.013661,0.044444,0.0,0.0,0.008315,1103.956850,18
2291,11,default_vehtype,10,0.644778,-73.983697,40.740947,0,1,0,1,...,0.016667,0.0,0.0,0.010076,0.016667,0.0,0.0,0.006352,1103.957173,19
2411,11,default_vehtype,1,0.644776,-73.983814,40.740787,0,1,0,1,...,0.017544,0.0,0.0,0.010672,0.017544,0.0,0.0,0.006682,1129.357496,20
2531,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,0,0,0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,21
2651,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,0,0,0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,22
2771,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,0,0,0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,23
2891,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,1,0,1,...,0.014085,0.0,0.0,0.008361,0.014085,0.0,0.0,0.005380,950.485800,24
3011,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,0,0,0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,25
3131,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,0,0,0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,26
3251,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,0,0,0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,27
3371,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,0,0,0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,28
3491,11,default_vehtype,0,0.644776,-73.983814,40.740787,0,0,0,0,...,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,29